name: ROS 2 CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 environment
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu lsb_release -cs main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y ros-humble-base python3-colcon-common-extensions

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip install -U colcon-common-extensions

      - name: Source ROS 2 environment
        run: echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV

      - name: Build ROS 2 workspace
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test
          colcon test-result --verbose
