name: ROS2 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2 environment
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y curl gnupg lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y ros-humble-base python3-colcon-common-extensions

    - name: Source ROS 2 environment
      run: echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV

    - name: Build the workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --packages-select my_package

    - name: Test the workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --packages-select my_package
        colcon test-result --verbose
