name: ROS 2 CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ROS_DISTRO: humble

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install -U colcon-common-extensions
        sudo apt-get install -y ros-$ROS_DISTRO-desktop

    - name: Initialize rosdep
      run: |
        sudo rosdep init
        rosdep update

    - name: Build workspace
      run: |
        source /opt/ros/$ROS_DISTRO/setup.bash
        colcon build --symlink-install
